### ISSUE TITLE
Compatibilidad en movil

### ISSUE THREAD

**Issue by KOKOSG7** [MaculaCSA/maculacsa.github.io#2]
No es compatible con móviles, por alguna razón el background no se rellena y los items no cambian de tamaño.
![image](https://user-images.githubusercontent.com/126774488/230765862-6a1053e1-4acb-479e-84ba-8e90f0aa2584.png)

**Comment by KOKOSG7** [comment]
arreglado

**Comment by PGSCOM** [comment]
Pues como esta arreglado cierra la Issue
