### ISSUE TITLE
Pat la patata confundido con el reparto de África

### ISSUE THREAD

**Issue by PGSCOM** [MaculaCSA/maculacsa.github.io#41]

**Comment by Laumf92** [comment]
Prometo aprender a usar esto para dejaros las cosas por aquí en vez de por Teams 😅

**Comment by PGSCOM** [comment]
Ya para el año que viene te enseñamos (Cuando estemos en TIC contigo)

> Prometo aprender a usar esto para dejaros las cosas por aquí en vez de por Teams 😅
