### ISSUE TITLE
Añadir modelos de categorías

### ISSUE THREAD

**Issue by PGSCOM** [MaculaCSA/maculacsa.github.io#83]

**Comment by PGSCOM** [comment]
Falta Documental, Animación y cartel

**Comment by Laumf92** [comment]
¿siguen faltando? Mañana puedo mandar  Héctor a ordenadores . O rogadle que lo haga esta tarde (si lo hace esta tarde le dejo que exponga el próximo día con el siguiente grupo en vez de mañana jajaja)

**Comment by PGSCOM** [comment]
Le he mandado por Teams un mensaje, el de documental está bien como está pero necesito uno para animación y otro para cartel. 

> ¿siguen faltando? Mañana puedo mandar Héctor a ordenadores . O rogadle que lo haga esta tarde (si lo hace esta tarde le dejo que exponga el próximo día con el siguiente grupo en vez de mañana jajaja)

@Laumf92
